# numpy

In [1]:
from numpy import *

### 初识

In [2]:
random.rand(4,4)

array([[ 0.38311961,  0.88168514,  0.98882693,  0.24826454],
       [ 0.01779948,  0.97131538,  0.26763739,  0.47210841],
       [ 0.99544715,  0.21137001,  0.92749406,  0.15683849],
       [ 0.36563555,  0.39946488,  0.70890836,  0.26477113]])

In [4]:
randMat = mat(random.rand(4,4)) # 将数组转化为矩阵
print(randMat)

[[ 0.97367917  0.03758767  0.95726989  0.28697613]
 [ 0.9003815   0.64151534  0.48019491  0.42069362]
 [ 0.83969068  0.87089087  0.42753312  0.51458974]
 [ 0.72198425  0.2659388   0.35478102  0.7986486 ]]


In [8]:
# 求逆
invRandMat = randMat.I
print(invRandMat)
# 乘法
myEye  = randMat*invRandMat
print(myEye)
# 误差
print(myEye - eye(4))

[[-1.49775925  8.41015652 -6.15252309  0.07230625]
 [ 0.09066808 -2.3960553   3.15451833 -0.80297792]
 [ 2.50067855 -7.40655     5.51625028 -0.55137213]
 [ 0.21292611 -3.51480374  2.06105041  1.69906438]]
[[  1.00000000e+00   9.64975887e-16  -4.82993835e-16   2.25178538e-17]
 [  1.18520350e-16   1.00000000e+00  -2.81687299e-16  -4.98458516e-17]
 [  2.12433290e-16  -9.65673021e-16   1.00000000e+00  -1.17443367e-17]
 [ -1.54835699e-16  -1.15735195e-17   5.62147777e-17   1.00000000e+00]]
[[  0.00000000e+00   9.64975887e-16  -4.82993835e-16   2.25178538e-17]
 [  1.18520350e-16  -7.77156117e-16  -2.81687299e-16  -4.98458516e-17]
 [  2.12433290e-16  -9.65673021e-16   4.44089210e-16  -1.17443367e-17]
 [ -1.54835699e-16  -1.15735195e-17   5.62147777e-17   0.00000000e+00]]


In [7]:
# 求转置
randMat.T

matrix([[ 0.97367917,  0.9003815 ,  0.83969068,  0.72198425],
        [ 0.03758767,  0.64151534,  0.87089087,  0.2659388 ],
        [ 0.95726989,  0.48019491,  0.42753312,  0.35478102],
        [ 0.28697613,  0.42069362,  0.51458974,  0.7986486 ]])

### 1.array

In [9]:
from numpy import array

In [10]:
mm = array((1,2,3))
pp = array((1,1,1))
pp+mm

array([2, 3, 4])

In [11]:
pp*2

array([2, 2, 2])

In [12]:
mm**2

array([1, 4, 9])

In [14]:
mm[1]

2

In [16]:
jj = array([[1,2,3],[1,1,1]])
jj[0]

array([1, 2, 3])

In [17]:
jj[0][1]

2

In [18]:
a1 = array([1,2,3])
a2 = array([0.3,0.2,0.3])
a1*a2

array([ 0.3,  0.4,  0.9])

### 2.matrix

In [19]:
from numpy import mat,matrix

In [20]:
ss = mat([1,2,3])
ss

matrix([[1, 2, 3]])

In [21]:
mm = matrix([1,2,3])
mm

matrix([[1, 2, 3]])

In [22]:
mm[0,1]

2

In [23]:
# 将列表转为矩阵
pyList = [1,2,3,100]
mat(pyList)

matrix([[  1,   2,   3, 100]])

In [24]:
mm*ss

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [25]:
mm*ss.T

matrix([[14]])

In [26]:
from numpy import shape

In [27]:
shape(mm)

(1, 3)

In [28]:
# 点乘
from numpy import multiply

In [29]:
multiply(mm,ss)

matrix([[1, 4, 9]])

In [30]:
mm.sort()
mm

matrix([[1, 2, 3]])

In [31]:
# argsort:得到排序的序号
dd = mat([4,5,1])
dd.argsort()

matrix([[2, 0, 1]])

In [32]:
# 均值
dd.mean()

3.3333333333333335

In [33]:
# 多维矩阵
jj = mat([[1,2,3],[8,8,8]])
shape(jj)

(2, 3)

In [34]:
jj[1,:]

matrix([[8, 8, 8]])

In [35]:
jj[1,0:2]

matrix([[8, 8]])

### 3.其他

In [36]:
from numpy import *

In [37]:
# 最大最小值
a = array([[1,2,3],[4,5,-6],[7,0,1]])

In [38]:
a.min()

-6

In [39]:
a.max()

7

In [41]:
# 求每行最大值组成的集合
a.max(axis=1)

array([3, 5, 7])

In [42]:
# 求每列最大值组成的集合
a.max(axis=0)

array([7, 5, 3])

In [43]:
a.min(0)

array([ 1,  0, -6])